version: "3.7"

services: 
  iredmail:
    image: iredmail/mariadb:stable

    container_name: iredmail_server
    env_file: .env
    volumes:
      - /etc/iredmail/data/backup-mysql:/var/vmail/backup/mysql 
      - /etc/iredmail/data/mailboxes:/var/vmail/vmail1 
      - /etc/iredmail/data/mlmmj:/var/vmail/mlmmj 
      - /etc/iredmail/data/mlmmj-archive:/var/vmail/mlmmj-archive 
      - /etc/iredmail/data/imapsieve_copy:/var/vmail/imapsieve_copy 
      - /etc/iredmail/data/custom:/opt/iredmail/custom 
      - /etc/iredmail/data/ssl:/opt/iredmail/ssl 
      - /etc/iredmail/data/mysql:/var/lib/mysql 
      - /etc/iredmail/data/clamav:/var/lib/clamav 
      - /etc/iredmail/data/sa_rules:/var/lib/spamassassin 
      - /etc/iredmail/data/postfix_queue:/var/spool/postfix 
    ports:
      - 80:80 
      - 443:443 
      - 110:110 
      - 995:995 
      - 143:143 
      - 993:993 
      - 25:25 
      - 465:465 
      - 587:587 
