version: "3"

services:
  lb-dev:
    image: nginx
    ports:
      - 8080:80
      # this will be 80:80 and 443:443 in production
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
