version: "3.7"

volumes:
  files:
    driver: local

services:
  vault:
    image: hashicorp/vault

    container_name: vault_server
    restart: always
    cap_add:
      - IPC_LOCK
    volumes:
      - files:/vault/data
      - files:/vault/files
      - files:/vault/logs
      # - files:/vault/config
      # - ./vault-config.json:/vault/config/vault-config.json 
    ports:
      - 8200:8200
    # command: 
    #   - "server"
    # environment:
    #   VAULT_LOCAL_CONFIG: >-
    #     {
    #       "storage": {
    #         "file": {
    #           "path": "/vault/data"
    #         }
    #       },
    #       "listener": {
    #         "tcp": {
    #           "address": "127.0.0.1:8200",
    #           "tls_disable": 1
    #         }
    #       },
    #       "api_addr": "http://127.0.0.1:8200",
    #       "cluster_addr": "https://127.0.0.1:8201",
    #       "ui": true
    #     }




