version: "3.7"

services: 
  vault:
    image: hashicorp/vault
    container_name: vault_server

    cap_add: 
      - IPC_LOCK
    volumes:
      - ./vault-config.json:/vault/config/vault-config.json
    ports:
      - 8200:8200
